package br.com.goals.hotcoffe;
/**
 * Representa um atributo de uma entidade
 * @author Fabio Issamu Oshiro
 *
 */
public class Attribute implements Cloneable {
	/**
	 * pode ser criado pelo pacote
	 */
	Attribute(){
	}
	boolean nullAble;
	int size;
	String className;
	Object value;
	boolean autoGeneratedValue;
	String name;
	Model parent;
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
